### ISSUE TITLE
Project hangs at `sbt` 

### ISSUE THREAD

**Issue by calvinbrown085** [twilio/sbt-guardrail#19]
When I add the dep `addSbtPlugin("com.twilio" % "sbt-guardrail" % "0.52.1")`

My sbt build hangs at 
```
Updating ProjectRef(uri
```

Has anyone seen this before?

**Comment by blast-hardcheese** [comment]
Great! I've also noticed this, from time to time, hopefully it'll get better now that coursier has been integrated into SBT 😄
