### ISSUE TITLE
Syncing packages to Maven Central

### ISSUE THREAD

**Issue by sideeffffect** [twilio/sbt-guardrail#3]
Hello,
could you please sync your packages from your custom BinTray repository `https://bintray.com/twilio/releases` to Maven Central `https://repo1.maven.org/maven2/`?
It will make them accessible to people behind corporate firewalls.

**Comment by blast-hardcheese** [comment]
@sideeffffect Related to a discussion in https://github.com/twilio/guardrail/issues/37 , I was unable to get the sbt-pgp plugin to do signing for me, which was preventing syncing to maven central. I'll see what I can do to resolve this though, sorry for the inconvenience

**Comment by sideeffffect** [comment]
have you also considered syncing to Bintray's [`JCenter`](https://bintray.com/bintray/jcenter)?

**Comment by blast-hardcheese** [comment]
Yeah, though I'm not super excited about putting my gpg private key into a text box on a website 😺

**Comment by sideeffffect** [comment]
so how do other people publish/sync to Maven Central? Surely there must be a way, because we're not the first ones with this use case...

I'm sorry I can't be of any more help, because I've never done this before :frown:

**Comment by sideeffffect** [comment]
sorry, let me rephraze that: do you think there is something I could help you with regarding this? Sadly I have no practical experience with sbt-pgp yet, but maybe I can research something or do something else?

**Comment by blast-hardcheese** [comment]
Nothing right now, just working through the issues with sbt-pgp that had blocked me before. As a stop-gap, you may consider running Guardrail via its CLI variant until these artifacts are published

**Comment by blast-hardcheese** [comment]
@sideeffffect guardrail 0.37.1-M1 (identical to 0.37.0, save for metadata changes required by sonatype) is now published on maven central. I'm still waiting for sbt-guardrail and guardrail-maven-plugin to sync, but they're on their way as well.

**Comment by blast-hardcheese** [comment]
Ah, I was just waiting for the search cache to clear. It turns out [sbt-guardrail](https://repo1.maven.org/maven2/com/twilio/sbt-guardrail_2.12_1.0/0.37.1-M1/) and [guardrail-maven-plugin](https://repo1.maven.org/maven2/com/twilio/guardrail-maven-plugin_2.12/) are both up, even though they don't currently show up in search.

**Comment by blast-hardcheese** [comment]
Now that they show up in the search, I'm closing this issue. Thanks for reporting, @sideeffffect!

**Comment by sideeffffect** [comment]
thank you so much @blast-hardcheese !!!
