### ISSUE TITLE
Publishing for 2.11

### ISSUE THREAD

**Issue by MelaHub** [twilio/sbt-guardrail#4]
Hello guys!
I still have a bunch of projects in scala 2.11 - I see that guardrail itself is crosscompiled but sbt-guardrail is not.

Any change to have it published for 2.11?

Thanks in advance!

**Comment by blast-hardcheese** [comment]
Fortunately, the 2.12 release is just to be compatible with sbt 1.x; you should have no problems using sbt 1.x + sbt-guardrail in any of your 2.11 projects.

**Comment by MelaHub** [comment]
Actually I've just realized that the problem is not scala 2.11 but sbt version 0.13 - I'll try to update :) 
Just out of curiosity - do you guys have any plan to support 0.13 too? I have the feeling that migrating to 1.2 from 0.13 is not going to be painless

**Comment by blast-hardcheese** [comment]
Unfortunately, it is no possible; scalameta is not available for 2.10, and backporting was not deemed worth it.

This was the main motivation behind having a CLI story, as we managed our generated code via makefile for over a year until the sbt 1.x issues were sorted.

Most plugins cross-compile now, so it should be largely painless, but Makefiles are always a last ditch option.

**Comment by MelaHub** [comment]
Thanks a lot!
