### ISSUE TITLE
Where to put specs yaml file? server.yaml is either incorrectly formatted or missing

### ISSUE THREAD

**Issue by sergeda** [twilio/sbt-guardrail#9]
I've got this error when trying to compile project with enabled sbt plugin:

> server.yaml is either incorrectly formatted or missing

I have server.yaml in my resources folder. And I have this code: 
```
guardrailTasks in Compile := List(
  Server(file("server.yaml"), pkg="com.nix.weg.server", tracing=true)
)
``` 
in build.sbt
Where should I put that server.yaml file?

**Comment by francescopellegrini** [comment]
`file(.)` references a file in your root directory. You need to prepend the path to your yaml file, e.g. `file("/src/main/resources/server.yaml")`

**Comment by sergeda** [comment]
> `file(.)` references a file in your root directory. You need to prepend the path to your yaml file, e.g. `file("/src/main/resources/server.yaml")`

Thanks. I had to add a point at start: `file("./src/main/resources/server.yaml")`
